app = "test-config-21"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  [[services.http_checks]]
    internal_port = 8080
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    [services.http_checks.headers]
        Host = "localhost"
        User-Agent = "curl/7.64.1"
        X-Forwarded-Port = "8080"
